### PR TITLE
Added a title parameter, for Constructor1 and Constructor2.

### LINKED ISSUE #7: Parameter update for the constructors.
It would be cosmetically nicer if Controller1's and Controller2's 
constructors received an extra parameter, a String, that they used in setting up 
their Frame's title, so that Main can ensure that all the instances of all the 
controllers are clearly distinguished on screen.  Do that now.  Remember that each 
constructor call in Main will need to be modified too to pass an extra actual 
parameter!  [The method call for setting the frame title is already present in the 
controller constructor bodies, it just needs altering.]  Each controller should also 
receive additional constructor parameters to indicate where on the screen it should 
be located.

### PR DESCRIPTION
**Pull request by GOCJM**
- This closes #7

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
I'm not sure why setTitle is being called twice - it's effectively overwriting itself. Unless I am missing something important - which can happen.

**Comment by GOCJM** [comment]
> I'm not sure why setTitle is being called twice - it's effectively overwriting itself. Unless I am missing something important - which can happen.

There is no parent `Controller` class, so this is fine for now. Maybe in a future release, this could be refactored.

**Review by ghost — COMMENTED** [review]
Should we leave this issue open as a future feature, fix it now or just ignore it?

**Comment by GOCJM** [comment]
> Should we leave this issue open as a future feature, fix it now or just ignore it?

This needs to be approved so I can merge the PR.

**Review by Gedyy — APPROVED** [review]

**Pull request merged**
